# SPDX-FileCopyrightText: 2026 Iyad
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = ["Cargo.toml", "Cargo.lock"]
SPDX-FileCopyrightText = "2026 Iyad"
SPDX-License-Identifier = "Apache-2.0"
